### ISSUE TITLE
Echopet Question

### ISSUE THREAD

**Issue by andrewkm** [Borlea/ArmorEquipEvent#8]
I see you blocked PMs on Spigot, jenkins down, github deleted.
Curious, did you jump ship? Can you provide source? Or perhaps you planning to go premium, cause if so I'm down to pay quite a bit. Sorry I'm posting here but I see no other way to contact you.

**Comment by kicjow** [comment]
@andrewkm this is not the place for that.

**Comment by andrewkm** [comment]
@kicjow how can I get in touch with @Borlea

**Comment by kicjow** [comment]
@andrewkm not sure but he mite reply here.

**Comment by Borlea** [comment]
I will reply here. I don't care the responses, I did the spigot stuff to ignore most of it.
EchoPet is a widely used plugin, but it needs to be replaced, badly.. Which is the reason for the github deletion, someone will most likely either spend hours of work getting it back to the state I had or use an already compiled jar and just deobfuscate it. Neither of these options I want to happen as someone with enough knowledge just has to make an efficiently coded plugin without any of the issues EchoPet experiences everyday(Entire server crashes, random tiny bugs, etc)

Obviously doing something like what I did(Deleting github) Will cause backlash but considering I'm pretty much entirely leaving the MC scene I wont experience anything..

The reason the maven/jenkins is done, it was hosted by a friend. One day he came to me and told me that they'll both be down for a bit while he changes how he hosts them. I said don't even put in the effort I'll just use this to shutdown development on the plugin.

Also please... someone.. make it support sponge
Also, I only picked up EchoPet because a server I was a developer on used it. Which I left awhile ago, and also recently shutdown.

**Comment by andrewkm** [comment]
This is totally understandable :)
Would you be willing to provide the source code to us so we don't have to go through the process of deobfuscstion?

Perhaps add us to the repo and let us fork it.
If you want a price for it we are happy to pay :)$

**Comment by andrewkm** [comment]
And as well good luck with your future endeavours @borlea - hope all is well :)!

**Comment by Borlea** [comment]
I have given my backup of it(Just going to each repo and downloading as zip, then put it all in a zip) To a the server owner. I have given him permission to do whatever with it but he'll have to contact you if he is willing to sell it.

Going to close this now.

**Comment by andrewkm** [comment]
Please have them contact me with the repo.

**Comment by andrewkm** [comment]
@borlea
